name: zip-release
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    # only allow on tags
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Create zip
        uses: papeloto/action-zip@v1
        with:
          files: index.js
          dest: release.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./release.zip
          fail_on_unmatched_files: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
